### ISSUE TITLE
doesn't work on tumbleweed

### ISSUE THREAD

**Issue by Kyr4l** [openSUSE/suseprime-appindicator#3]
Traceback (most recent call last):
  File "/usr/bin/suseprime-appindicator", line 11, in <module>
    from suseprimeindicator import indicator
  File "/usr/lib/python3.11/site-packages/suseprimeindicator/indicator.py", line 11, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available

**Comment by loony114** [comment]
Just faced the same issue. Could easily be fixed just by installing package

typelib-1_0-Notify-0_7

(apart from two additional broken dependencies I encountered...)
